name: Documentation

on:
  # manual trigger
  workflow_dispatch:
  # trigger from an other action (e.g. as last step of the example action after example building)
  repository_dispatch:
    types: [trigger-docu]

  pull_request:
  push:
    branches: 
      - main
    paths:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/Documentation.yml'
    tags: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'
          arch: x64

      - name: "Copy examples from examples branch and readme from main"
        env:
          WORK_TREE: './docs/src/examples'
          SRC_BRANCH: 'origin/examples'
          SRC_FOLDER_PATH: 'examples'
        # copy the examples from the examples branch (jupyter: .md, .fmu, .svg, .gif; pluto: .html) ("|| true" for optional files, else command will fail) and the readme from main
        # as jupyter-src must contain md and svg files, those are not optional (if there are examples with plots in the repo), therefr they are not combined with a "|| true"
        # all jupyter examples are moved out of the jupyter-src folder into the docs-src-examples folder, pluto examples are not. Those are provided to the documentation within their pluto-src folder. 
        run: |
          git fetch
          git --work-tree=$WORK_TREE checkout $SRC_BRANCH -- $SRC_FOLDER_PATH/jupyter-src/*.md 
          git --work-tree=$WORK_TREE checkout $SRC_BRANCH -- $SRC_FOLDER_PATH/jupyter-src/*.svg
          git --work-tree=$WORK_TREE checkout $SRC_BRANCH -- $SRC_FOLDER_PATH/jupyter-src/*.gif || true
          git --work-tree=$WORK_TREE checkout $SRC_BRANCH -- $SRC_FOLDER_PATH/jupyter-src/*.fmu || true
          git --work-tree=$WORK_TREE checkout $SRC_BRANCH -- $SRC_FOLDER_PATH/pluto-src/*.html && mkdir -p $WORK_TREE/pluto-src && mv $WORK_TREE/$SRC_FOLDER_PATH/pluto-src/* $WORK_TREE/pluto-src || true
          mv $WORK_TREE/$SRC_FOLDER_PATH/jupyter-src/* $WORK_TREE 
          rm -r $WORK_TREE/$SRC_FOLDER_PATH
          cp ./README.md ./docs/src/index.md

      - name: "Install dependencies"
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: "Build and deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl